name: Maven Build and Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: blaromack/k8s-deploy-helper-github:1.0.0
      #   options: --privileged
      # docker-in-dind:
      #   image: docker:stable-dind
      #   options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    # Perform Maven build
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Maven
      run: |
        apk add -U maven
    - name: Install zlib
      run: apk add --no-cache zlib

    - name: Run Maven tests
      run: mvn test
      env:
        JAVA_HOME: /__t/Java_Adopt_jdk/17.0.8-7/x64


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: check base
      run: ls -l
    - name: Build code
      run: |
        command build
       