name: Maven Build and Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    services:
      k8s-deploy-helper:
        image: quay.io/lifechurch/k8s-deploy-helper:3.0.0
        options: --privileged
      docker-in-dind:
        image: docker:stable-dind
        options: --privileged

    steps:
    # Checkout the code
    - name: Checkout
      uses: actions/checkout@v2

    # Perform Maven build
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Maven Build
      run: mvn clean install

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: BuildPack
      run: |
        docker info  # this is just to check that Docker is running
        command build
      env:
        DOCKER_HOST: tcp://docker-in-dind:2375

    # Build and push Docker image
    - name: Build Dockerfile
      run: |
        # Your commands to interact with k8s-deploy-helper here
        command build
      env:
        DOCKER_HOST: tcp://k8s-deploy-helper:2375

    - name: Push Docker
      run: |
        # Your commands to interact with k8s-deploy-helper here
        command push
      env:
        DOCKER_HOST: tcp://k8s-deploy-helper:2375

    # Deploy to Kubernetes
    # - name: Deploy to Kubernetes
    #   run: |
    #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yml
    #     kubectl apply -f your-k8s-manifest.yml  # Replace with the path to your Kubernetes manifest
    #   env:
    #     KUBECONFIG: kubeconfig.yml

